### ISSUE TITLE
Context.resolveAttribute crashes the consuming app on Oppo devices running on Android 10 & 11

### ISSUE THREAD

**Issue by himanshu-bb** [Backbase/DeferredResources#84] opened 2022-06-10 13:34 UTC
**Priority and business impact**

The business impact is high as all the Oppo device users are affected. They are not able to use the app as it crashes as soon as the app launches.

**Description**

The theme attribute (android.R.attr.navigationBarColor) fails to resolve using Deferred Resources as seen in the stacktrace. Please see attached screenshots for more information.

**Steps to reproduce**

Install & launch the consumer app on the attached Oppo Android devices running API level 30 & 31.

**Current behaviour (the bug)**

The consumer app crashes as soon it's opened by the user.

**Expected behaviour**

The consumer app should be usable.

**Caller code**

```
val navigationBarColor = DeferredColor.Attribute(android.R.attr.navigationBarColor).resolve(this)
```

**Exception thrown from**

```
internal inline fun <T> Context.resolveAttribute(
    @AttrRes resId: Int,
    attributeTypeName: String,
    reusedTypedValue: TypedValue,
    vararg expectedTypes: Int,
    resolveRefs: Boolean = true,
    toTypeSafeResult: TypedValue.() -> T
): T {
    try {
        val isResolved = theme.resolveAttribute(resId, reusedTypedValue, resolveRefs)
        if (isResolved && expectedTypes.contains(reusedTypedValue.type))
            return reusedTypedValue.toTypeSafeResult()
        else
            throw IllegalArgumentException(createErrorMessage(resId, attributeTypeName, isResolved))
    } finally {
        // Clear for re-use:
        reusedTypedValue.setTo(EMPTY_TYPED_VALUE)
    }
}
```

<img width="1410" alt="playstore1" src="https://user-images.githubusercontent.com/65217822/173076718-1389a2d2-e110-445e-a13f-c16dbe9a5a91.png">
<img width="1402" alt="playstore3" src="https://user-images.githubusercontent.com/65217822/173076744-68aaae49-cbe1-4311-b05a-a4997f96cc5b.png">
<img width="1641" alt="playstore4" src="https://user-images.githubusercontent.com/65217822/173076748-83d598ea-fefe-4acb-9bf6-1d8b4dade39f.png">

**Comment by himanshu-bb** [comment] 2022-06-10 13:35
@drewhamilton Please provide insights into the issue.

**Comment by himanshu-bb** [comment] 2022-06-14 11:02
Please find below the complete stacktrace, apparently there are three space characters where the descriptive message should have been.

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3537)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3692)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:140)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:100)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2235)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:240)
  at android.app.ActivityThread.main (ActivityThread.java:7829)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:512)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1027)
Caused by: java.lang.IllegalArgumentException:    at com.backbase.deferredresources.DeferredColor$Attribute.d(SourceFile:9)
        at com.backbase.android.retail.journey.app.common.AppActivity.k(SourceFile:2)
        at com.backbase.android.retail.journey.app.common.AppActivity.onCreate(SourceFile:1)
        at com.stanbicbankonline.app.MainActivity.onCreate(SourceFile:1)
        at android.app.Activity.performCreate(Activity.java:7980)
        at android.app.Activity.performCreate(Activity.java:7969)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3508)
        ... 11 more
```

**Comment by drewhamilton** [comment] 2022-06-14 22:11
Seems like the error message is being removed by a code obfuscation tool. What obfuscation tool is being used? Is it possible to adjust its settings to not strip the strings used to [create this error message](https://github.com/Backbase/DeferredResources/blob/main/deferred-resources/src/main/java/com/backbase/deferredresources/internal/Context.kt#L70-L80)?

Or, can you reproduce this on an Oppo device on a non-obfuscated build? It's going to be hard to pinpoint this issue otherwise. Could be that Oppo has removed this resource for some reason, or that it's set to an invalid type (maybe a color selector rather than a single color?).

**Comment by paristote** [comment] 2022-06-15 09:35
Thanks @drewhamilton for your help 👍 
We're trying to get our hands on one of the Oppo devices so we can reproduce.

**Comment by drewhamilton** [comment] 2023-02-16 18:18
Closing this because it hasn't been updated in awhile and it appears to be a theme issue rather than a Deferred Resources issue per se. Feel free to comment if it should be reopened.

**Closed by drewhamilton** 2023-02-16 18:18 UTC
Labels: bug
